-- Preserve the verified workbook's country-specific indicator labels. Earlier
-- managed-workbook imports could accidentally replace them with provider event
-- names; provider labels belong only to macro_feed_release_events.
UPDATE macro_excel_indicator_mappings SET source_label='CPI y/y' WHERE currency='AUD' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP q/q' WHERE currency='AUD' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='Cash Rate' WHERE currency='AUD' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='Employment Change' WHERE currency='AUD' AND source_indicator_key='nfp';
UPDATE macro_excel_indicator_mappings SET source_label='Trimmed Mean CPI m/m' WHERE currency='AUD' AND source_indicator_key='pce_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='PPI q/q' WHERE currency='AUD' AND source_indicator_key='ppi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Household Spending m/m' WHERE currency='AUD' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate' WHERE currency='AUD' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='CPI m/m' WHERE currency='CAD' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP MoM' WHERE currency='CAD' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='Overnight Rate' WHERE currency='CAD' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='Employment Change' WHERE currency='CAD' AND source_indicator_key='nfp';
UPDATE macro_excel_indicator_mappings SET source_label='Median CPI y/y' WHERE currency='CAD' AND source_indicator_key='pce_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales m/m' WHERE currency='CAD' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate' WHERE currency='CAD' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='KOF Economic Barometer' WHERE currency='CHF' AND source_indicator_key='consumer_confidence';
UPDATE macro_excel_indicator_mappings SET source_label='CPI m/m' WHERE currency='CHF' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP q/q (sport-event adjusted)' WHERE currency='CHF' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='SNB Policy Rate' WHERE currency='CHF' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='procure.ch Manufacturing PMI' WHERE currency='CHF' AND source_indicator_key='manufacturing_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Producer and Import Prices m/m' WHERE currency='CHF' AND source_indicator_key='ppi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales y/y' WHERE currency='CHF' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate SA' WHERE currency='CHF' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='CPI y/y' WHERE currency='CNY' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP q/y' WHERE currency='CNY' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='1-Year Loan Prime Rate' WHERE currency='CNY' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='NBS Manufacturing PMI' WHERE currency='CNY' AND source_indicator_key='manufacturing_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='PPI y/y' WHERE currency='CNY' AND source_indicator_key='ppi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales y/y' WHERE currency='CNY' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='NBS Non Manufacturing PMI' WHERE currency='CNY' AND source_indicator_key='services_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Urban Surveyed Unemployment Rate' WHERE currency='CNY' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='Consumer Confidence Final' WHERE currency='EUR' AND source_indicator_key='consumer_confidence';
UPDATE macro_excel_indicator_mappings SET source_label='CPI Flash Estimate y/y' WHERE currency='EUR' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP Growth Rate QoQ Flash' WHERE currency='EUR' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='ECB Deposit Facility Rate' WHERE currency='EUR' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='HCOB Flash Manufacturing PMI' WHERE currency='EUR' AND source_indicator_key='manufacturing_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Final Employment Change q/q' WHERE currency='EUR' AND source_indicator_key='nfp';
UPDATE macro_excel_indicator_mappings SET source_label='Core CPI Flash Estimate y/y' WHERE currency='EUR' AND source_indicator_key='pce_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales m/m' WHERE currency='EUR' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='HCOB Flash Services PMI' WHERE currency='EUR' AND source_indicator_key='services_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate' WHERE currency='EUR' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='GfK Consumer Confidence' WHERE currency='GBP' AND source_indicator_key='consumer_confidence';
UPDATE macro_excel_indicator_mappings SET source_label='CPI y/y' WHERE currency='GBP' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Monthly GDP m/m' WHERE currency='GBP' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='Bank of England Bank Rate' WHERE currency='GBP' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='S&P Global Flash Manufacturing PMI' WHERE currency='GBP' AND source_indicator_key='manufacturing_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Core CPI y/y' WHERE currency='GBP' AND source_indicator_key='pce_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='PPI Output m/m' WHERE currency='GBP' AND source_indicator_key='ppi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales Volume m/m' WHERE currency='GBP' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='S&P Global Flash Services PMI' WHERE currency='GBP' AND source_indicator_key='services_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Claimant Count Change' WHERE currency='GBP' AND source_indicator_key='unemployment_claims';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate (3m ending)' WHERE currency='GBP' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='Tankan Manufacturing Index' WHERE currency='JPY' AND source_indicator_key='consumer_confidence';
UPDATE macro_excel_indicator_mappings SET source_label='Prelim GDP q/q' WHERE currency='JPY' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='BoJ Policy Rate' WHERE currency='JPY' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='Jobs-to-Applicants Ratio' WHERE currency='JPY' AND source_indicator_key='jolts';
UPDATE macro_excel_indicator_mappings SET source_label='Jibun Bank Flash Manufacturing PMI' WHERE currency='JPY' AND source_indicator_key='manufacturing_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='National Core CPI y/y' WHERE currency='JPY' AND source_indicator_key='pce_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Corporate Goods Price Index y/y' WHERE currency='JPY' AND source_indicator_key='ppi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Jibun Bank Flash Services PMI' WHERE currency='JPY' AND source_indicator_key='services_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate' WHERE currency='JPY' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='Consumers price index (CPI)' WHERE currency='NZD' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP q/q' WHERE currency='NZD' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='Official Cash Rate' WHERE currency='NZD' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='Employment Change q/q' WHERE currency='NZD' AND source_indicator_key='nfp';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales q/q' WHERE currency='NZD' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate' WHERE currency='NZD' AND source_indicator_key='unemployment_rate';
UPDATE macro_excel_indicator_mappings SET source_label='CB Consumer Confidence' WHERE currency='USD' AND source_indicator_key='consumer_confidence';
UPDATE macro_excel_indicator_mappings SET source_label='CPI m/m' WHERE currency='USD' AND source_indicator_key='cpi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='GDP Growth Rate QoQ Adv' WHERE currency='USD' AND source_indicator_key='gdp';
UPDATE macro_excel_indicator_mappings SET source_label='Federal Funds Target Range Upper Bound' WHERE currency='USD' AND source_indicator_key='interest_rates';
UPDATE macro_excel_indicator_mappings SET source_label='JOLTS Job Openings' WHERE currency='USD' AND source_indicator_key='jolts';
UPDATE macro_excel_indicator_mappings SET source_label='ISM Manufacturing PMI' WHERE currency='USD' AND source_indicator_key='manufacturing_pmi';
UPDATE macro_excel_indicator_mappings SET source_label='Non-Farm Employment Change' WHERE currency='USD' AND source_indicator_key='nfp';
UPDATE macro_excel_indicator_mappings SET source_label='Core PCE Price Index m/m' WHERE currency='USD' AND source_indicator_key='pce_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='PPI m/m' WHERE currency='USD' AND source_indicator_key='ppi_yoy';
UPDATE macro_excel_indicator_mappings SET source_label='Retail Sales m/m' WHERE currency='USD' AND source_indicator_key='retail_sales';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Claims' WHERE currency='USD' AND source_indicator_key='unemployment_claims';
UPDATE macro_excel_indicator_mappings SET source_label='Unemployment Rate' WHERE currency='USD' AND source_indicator_key='unemployment_rate';
